#!/usr/bin/env python3
"""Generate the Kotlin compatibility matrix from data/compatibility.json."""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "data" / "compatibility.json"
OUTPUT = (
    REPO_ROOT
    / "lsposed/app/src/main/kotlin/dev/soranerai/vpnhidenext/generated/CompatibilityMatrix.kt"
)
COMPONENTS = ("lsposed", "bridge", "built-in", "kmod")
VERSION_RE = re.compile(r"^v?\d+(?:\.\d+){1,2}(?:[-+][0-9A-Za-z.-]+)?$")


def kotlin_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_releases() -> list[dict[str, str]]:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    if data.get("schema") != 1:
        raise SystemExit("error: compatibility.json has unsupported schema")
    releases = data.get("releases")
    if not isinstance(releases, list) or not releases:
        raise SystemExit("error: compatibility.json must contain releases[]")

    result: list[dict[str, str]] = []
    for index, release in enumerate(releases):
        if not isinstance(release, dict):
            raise SystemExit(f"error: releases[{index}] must be an object")
        missing = [component for component in COMPONENTS if component not in release]
        if missing:
            raise SystemExit(f"error: releases[{index}] missing {', '.join(missing)}")
        row = {component: str(release[component]).strip() for component in COMPONENTS}
        for component, version in row.items():
            if not VERSION_RE.fullmatch(version):
                raise SystemExit(
                    f"error: releases[{index}].{component} has invalid version {version!r}"
                )
        result.append(row)
    return result


def render(releases: list[dict[str, str]]) -> str:
    lines = [
        "// Generated by scripts/codegen-compatibility.py; do not edit manually.",
        "package dev.soranerai.vpnhidenext.generated",
        "",
        "internal data class CompatibleRelease(",
        "    val lsposed: String,",
        "    val bridge: String,",
        "    val builtIn: String,",
        "    val kmod: String,",
        ")",
        "",
        "internal val compatibilityMatrix: List<CompatibleRelease> = listOf(",
    ]
    for release in releases:
        lines.extend(
            [
                "    CompatibleRelease(",
                f"        lsposed = {kotlin_string(release['lsposed'])},",
                f"        bridge = {kotlin_string(release['bridge'])},",
                f"        builtIn = {kotlin_string(release['built-in'])},",
                f"        kmod = {kotlin_string(release['kmod'])},",
                "    ),",
            ]
        )
    lines.extend([")", ""])
    return "\n".join(lines)


def main() -> int:
    OUTPUT.write_text(render(load_releases()), encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
