#!/usr/bin/env python3
"""Generate the Kotlin compatibility matrix from data/compatibility.json."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TypedDict

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "data" / "compatibility.json"
OUTPUT = (
    REPO_ROOT
    / "lsposed/app/src/main/kotlin/dev/soranerai/vpnhidenext/generated/CompatibilityMatrix.kt"
)
SCALAR_COMPONENTS = ("lsposed", "bridge", "kmod")
COMPONENTS = (*SCALAR_COMPONENTS, "built-in")
VERSION_RE = re.compile(r"^v?\d+(?:\.\d+){1,2}(?:[-+][0-9A-Za-z.-]+)?$")


class Release(TypedDict):
    lsposed: str
    bridge: str
    built_in: list[str]
    kmod: str


def kotlin_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def normalize_version(value: object, field: str) -> str:
    if not isinstance(value, str):
        raise SystemExit(f"error: {field} must be a version string")
    version = value.strip()
    if not VERSION_RE.fullmatch(version):
        raise SystemExit(f"error: {field} has invalid version {version!r}")
    return version


def load_releases(source: Path = SOURCE) -> list[Release]:
    data = json.loads(source.read_text(encoding="utf-8"))
    if data.get("schema") != 1:
        raise SystemExit("error: compatibility.json has unsupported schema")
    releases = data.get("releases")
    if not isinstance(releases, list) or not releases:
        raise SystemExit("error: compatibility.json must contain releases[]")

    result: list[Release] = []
    for index, release in enumerate(releases):
        if not isinstance(release, dict):
            raise SystemExit(f"error: releases[{index}] must be an object")
        missing = [component for component in COMPONENTS if component not in release]
        if missing:
            raise SystemExit(f"error: releases[{index}] missing {', '.join(missing)}")
        row: Release = {
            "lsposed": normalize_version(release["lsposed"], f"releases[{index}].lsposed"),
            "bridge": normalize_version(release["bridge"], f"releases[{index}].bridge"),
            "built_in": [],
            "kmod": normalize_version(release["kmod"], f"releases[{index}].kmod"),
        }
        raw_built_in = release["built-in"]
        if isinstance(raw_built_in, str):
            built_in = [normalize_version(raw_built_in, f"releases[{index}].built-in")]
        elif isinstance(raw_built_in, list) and raw_built_in:
            built_in = [
                normalize_version(version, f"releases[{index}].built-in[{built_in_index}]")
                for built_in_index, version in enumerate(raw_built_in)
            ]
            if len(set(built_in)) != len(built_in):
                raise SystemExit(f"error: releases[{index}].built-in has duplicate versions")
        else:
            raise SystemExit(
                f"error: releases[{index}].built-in must be a version string or non-empty array"
            )
        row["built_in"] = built_in
        result.append(row)
    return result


def kotlin_strings(values: list[str]) -> str:
    return "listOf(" + ", ".join(kotlin_string(value) for value in values) + ")"


def render(releases: list[Release]) -> str:
    lines = [
        "// Generated by scripts/codegen-compatibility.py; do not edit manually.",
        "package dev.soranerai.vpnhidenext.generated",
        "",
        "internal data class CompatibleRelease(",
        "    val lsposed: String,",
        "    val bridge: String,",
        "    val builtIn: List<String>,",
        "    val kmod: String,",
        ")",
        "",
        "internal val compatibilityMatrix: List<CompatibleRelease> =",
        "    listOf(",
    ]
    for release in releases:
        lines.extend(
            [
                "        CompatibleRelease(",
                f"            lsposed = {kotlin_string(release['lsposed'])},",
                f"            bridge = {kotlin_string(release['bridge'])},",
                f"            builtIn = {kotlin_strings(release['built_in'])},",
                f"            kmod = {kotlin_string(release['kmod'])},",
                "        ),",
            ]
        )
    lines.extend(["    )", ""])
    return "\n".join(lines)


def main() -> int:
    OUTPUT.write_text(render(load_releases()), encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
